language: ruby
rvm: 2.7.0
sudo: false
cache: bundler
bundler_args: --without production
# env:
#   global:
#     - CC_TEST_REPORTER_ID=9304a224f589e6c530a89794c91c4e4c33fe571b4099c9e968ba10d837a5fc99
#     - CCTR=/tmp/cc-test-reporter
# before_install:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
#   - chmod +x $CCTR
#   - $CCTR before-build
# script:
#   - bundle exec rake db:setup
#   - bundle exec rake spec
#   - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
#   - bundle exec rake cucumber
#   - $CCTR format-coverage  --output coverage/codeclimate.$SUITE.json 
# # after_script:
# #   - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
# #   - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT
# after_script:
#   - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
#   - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
#   - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
#   - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
env:
  global:
    - CC_TEST_REPORTER_ID=9304a224f589e6c530a89794c91c4e4c33fe571b4099c9e968ba10d837a5fc99
language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT